/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import { useMemo, useRef, useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  const customMaterials = useMemo(() => {
    return {
      curtainMaterial: new THREE.MeshPhongMaterial({ color: "#d90429" }),
      bodyMaterial: new THREE.MeshPhongMaterial({ map: matcapTexture }),
      tableMaterial: new THREE.MeshPhongMaterial({ color: "#582f0e" }),
      radiatorMaterial: new THREE.MeshPhongMaterial({ color: "#fff" }),
      compMaterial: new THREE.MeshStandardMaterial({ color: "#fff" }),
      pillowMaterial: new THREE.MeshPhongMaterial({ color: "#8338ec" }),
      chairMaterial: new THREE.MeshPhongMaterial({ color: "#000" }),
    };
  }, [matcapTexture]);

  useEffect(() => {
    // Dispose materials on component unmount
    return () => {
      Object.values(customMaterials).forEach((material) => {
        if (material.map) {
          material.map.dispose();
        }
        material.dispose();
      });
    };
  }, [customMaterials]);

  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1.5} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._________6_blinn1_0.geometry}
        material={customMaterials.curtainMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body1_blinn1_0.geometry}
        material={customMaterials.bodyMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabin_blinn1_0.geometry}
        material={customMaterials.tableMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={customMaterials.chairMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.comp_blinn1_0.geometry}
        material={customMaterials.compMaterial}
      />
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillows_blinn1_0.geometry}
        material={customMaterials.pillowMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.radiator_blinn1_0.geometry}
        material={customMaterials.radiatorMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_blinn1_0.geometry}
        material={customMaterials.tableMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");
